#define BYREFLIKE_GENERIC_CONSTRAINT "byreflike"
#define MEMORY_ASSEMBLY "System.Runtime"
#define SPAN_ASSEMBLY "CORE_ASSEMBLY"
#define HAS_MEMORY_MARSHAL_CREATE_SPAN
#define HAS_AGGRESSIVE_OPTIMIZATION
#define NET7_0_OR_GREATER
