#define BYREFLIKE_GENERIC_CONSTRAINT ""
#define HAS_MEMORY_MARSHAL_CREATE_SPAN
#define HAS_AGGRESSIVE_OPTIMIZATION
#define MEMORY_ASSEMBLY "System.Memory"
#define SPAN_ASSEMBLY "CORE_ASSEMBLY"

.assembly extern MEMORY_ASSEMBLY
{
	.publickeytoken = ( CC 7B 13 FF CD 2D DD 51 )
	.ver 4:2:1:0
}
