#define BYREFLIKE_GENERIC_CONSTRAINT ""
#define MEMORY_ASSEMBLY "System.Memory"
#define SPAN_ASSEMBLY "CORE_ASSEMBLY"
#define HAS_MEMORY_MARSHAL_CREATE_SPAN
#define HAS_AGGRESSIVE_OPTIMIZATION
#define NET7_0_OR_GREATER

.assembly extern MEMORY_ASSEMBLY
{
	.publickeytoken = ( CC 7B 13 FF CD 2D DD 51 )
	.ver CORE_ASSEMBLY_VERSION
}
